class AuthError(Exception):
    pass


class SalesforceError(Exception):
    pass


class ExecutionError(Exception):
    pass
